server:
  mode: 'test'
  defaultPageSize: 10 # 默认分页条数
  maxPageSize: 500    # 最大分页条数
  fileUploadPath: './' # 文件上传路径
  fileHostUrl: 'http://127.0.0.1:9527/' # 文件访问域名
jwt:
  tokenExpire: 864000   # token过期时间
  tokenKey: 'Authorization' # token的键名
  tokenIssuer: 'gin-framework'
  secret: '3jQSRZXeXzr09hq0GrZuL9Dgtk2XV9Ax'
log:
  debug: true
  fileName: 'mqenergy-go' # 日志文件名称
  dirPath: 'runtime/logs' # 日志默认存放目录
mysql:
  - host: '127.0.0.1'
    port: '3306'
    user: 'root'
    password: '123456'
    dbname: 'gin_framework'
    prefix: ""
    maxIdleConns: 10 # 设置空闲连接池中连接的最大数量
    maxOpenConns: 100 # 设置打开数据库连接的最大数量
    maxLifeTime: 60 # 设置了连接可复用的最大时间（分钟）
    logLevel: 3 # 日志模式 1:slient 2:error 3:warn 4:info
redis:
  host: '127.0.0.1'
  port: '6379'
  password: '123456'
  dbNum: 0
  loginPrefix: 'gin_framework_login_' # 登录用户存入redis键名的前缀
amqp:
  host: '127.0.0.1'
  port: '5672'
  user: 'guest'
  password: ''
  vhost: ''
oss:
  endPoint: 'https://oss-cn-shanghai.aliyuncs.com'
  accessKeyId: ''
  accessKeySecret: ''
  bucketName: ''
